FROM jarosenb/uvposit

ADD . /opt/webapp/
WORKDIR /opt/webapp

RUN adduser -D myuser
USER myuser

# Run the app.  CMD is required to run on Heroku
# $PORT is set by Heroku
CMD gunicorn --bind 0.0.0.0:$PORT wsgi --reload
